name: Testes Automatizados .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar o projeto
      run: dotnet build --no-restore --configuration Release

    - name: Executar os testes
      run: dotnet test --no-build --configuration Release --verbosity normal
