name: Testes Automatizados .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar SDK do .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências da API
      run: dotnet restore ./ServidorPublico.API/ServidorPublico.API.csproj

    - name: Restaurar dependências dos testes
      run: dotnet restore ./ServidorPublico.Tests/ServidorPublico.Tests.csproj

    - name: Compilar a API
      run: dotnet build ./ServidorPublico.API/ServidorPublico.API.csproj --no-restore --configuration Release

    - name: Compilar os testes
      run: dotnet build ./ServidorPublico.Tests/ServidorPublico.Tests.csproj --no-restore --configuration Release

    - name: Executar os testes unitários
      run: dotnet test ./ServidorPublico.Tests/ServidorPublico.Tests.csproj --no-build --configuration Release --verbosity normal
